### PR TITLE
Support GraphiteReporter configuration from app.config

### PR DESCRIPTION
**Pull request by slawwan**
Hello guys!

Now I have to configure GraphiteReporter from app.config inside my project, becauase Metrics.Net supports only CSVReporter configuration.

Here is an attempt to do GraphiteReporter configuration inside Metrics.Net as it's done for CSVReporter.

### CODE REVIEW

**Comment by Pliner** [comment]
:+1:

**Comment by slawwan** [comment]
@PaulParau have you had a chance to look into this PR?

**Comment by PaulParau** [comment]
@slawwan not yet, I'll look into it as soon as I can though.

**Comment by PaulParau** [comment]
Hey, I got a change to look at this PR (sorry it took so long), and I think we should move the logic contained in the `ConfigureGraphiteReporter` method to a new extension method in `GraphiteExtensions` (e.g. `WithGraphiteFromConfig()`). This decouples the core configuration (`MetricsConfig`) from the Graphite-specific configuration and is necessary for the Graphite reporter to be separated into its own project later on (which we plan to do).

Let me know your thoughts on this. I can make the change myself after accepting the PR, it's trivial.

**Comment by slawwan** [comment]
I've moved configuration code to GraphiteExtensions. But now I have some doubts about logging on else branches in new method. Please, look at my solution. If you have any ideas how to make it better, I not mind.

**Comment by PaulParau** [comment]
Here's what I think: I'd rather throw an exception instead of logging errors/warnings. Since you're explicitly calling WithGraphiteFromConfig(), it means that you expect the values to be present in the config file and to be correct (i.e. valid URI & interval). If this is not the case, it means that your application is misconfigured and you don't want configuration to proceed.

Let me know what you think.

**Comment by slawwan** [comment]
1. I agree wih idea "throw an exception instead of logging"
2. I like the idea to disable reporter by empty settings. I need to control it from config, [like CsvConfig](https://github.com/Recognos/Metrics.NET/blob/master/Src/Metrics/MetricsConfig.cs#L278). We use this logic in our application for graphite reporter.

So, there is new version:

`private static void WithGraphiteFromConfig(this MetricsReports reports)
{
    var graphiteMetricsUri = ConfigurationManager.AppSettings["Metrics.Graphite.Uri"];
    var graphiteMetricsInterval = ConfigurationManager.AppSettings["Metrics.Graphite.Interval.Seconds"];

    if (!string.IsNullOrEmpty(graphiteMetricsUri) && !string.IsNullOrEmpty(graphiteMetricsInterval))
    {
        Uri uri;
        if (!Uri.TryCreate(graphiteMetricsUri, UriKind.Absolute, out uri))
        {
            throw new Exception("Invalid Metrics Configuration: Metrics.Graphite.Uri must be a valid absolute URI");
        }
        int seconds;
        if (!int.TryParse(graphiteMetricsInterval, out seconds) || seconds <= 0)
        {
            throw new Exception("Invalid Metrics Configuration: Metrics.Graphite.Interval.Seconds Seconds must be an integer > 0");
        }
        reports.WithGraphite(uri, TimeSpan.FromSeconds(seconds));
    }
}`

**Comment by PaulParau** [comment]
When I initially merged this (v0.4.2-pre), I made it so an exception was thrown if the config keys were missing.

What you're saying makes sense, so I've modified it now: if any of the config keys are missing, the reporter is disabled (I've also logged this to decrease the chances of the reporter being disabled by mistake). You can have a look [here](https://github.com/Recognos/Metrics.NET/blob/master/Src/Metrics/Graphite/GraphiteExtensions.cs).

Thanks for all your help!

**Pull request merged**
