### PR TITLE
Add support for InfluxDB v0.9.1+

### PR DESCRIPTION
**Pull request by Paccc**
The JSON protocol, which is currently being used by the InfluxDB reporter, has been [deprecated](https://docs.influxdata.com/influxdb/v0.13/write_protocols/json/) and removed in InfluxDB versions greater than v0.9.1. The expected way to write metric data to InfluxDB is using the [LineProtocol syntax](https://docs.influxdata.com/influxdb/v0.13/write_protocols/line/) defined in the InfluxDB docs.

This pull request adds support for the newer versions of InfluxDB using the new syntax. Support for the HTTP and UDP protocol have both been added as well. The InfluxDB report has also been refactored to separate the writing process into a separate `InfluxdbWriter` which is responsible for writing the data using the whichever protocol is chosen. This also allows extending the model to support other or future types of protocols and formats defined by InfluxDB.

Writing data to InfluxDB is done in 3 different and extendable steps:
- `InfluxdbConverter`: Converts the metric data into `InfluxRecords`, which are the data model object for InfluxDB datapoints.
- `InfluxdbFormatter`: Formats the metric name and tag/field names used in the InfluxDB tables. This can convert all names to lowercase or replace any spaces with underscores, for example.
- `InfluxdbWriter`: Writes the `InfluxRecords` to the database. Derived implementations exist for the HTTP and UDP protocols.

Configuration can be done using the different overloads of the `MetricsReports` configuration object. For example, the following code will add an InfluxDB reporter using the HTTP protocol for a database named `testdb` on host `10.0.10.24:80`:

```
Metric.Config
    .WithReporting(report => report
        .WithInfluxDbHttp("10.0.10.24", "testdb", reportInterval, null, c => c
            .WithConverter(new DefaultConverter().WithGlobalTags("host=web1,env=dev"))
            .WithFormatter(new DefaultFormatter().WithLowercase(true))
            .WithWriter(new InfluxdbHttpWriter(c, 1000))));
```

I read on another discussion here about separating the reporters out into separate projects to reduce the amount of code in the main Metrics.NET nuget package, and this one might be a good candidate for that at some point. The code here has no external dependencies so it could be included in the current repo without adding any extra libs, and then maybe removed in a later Metrics.NET version. I'd be happy to move this to a separate repo if you think that's best.

I also added unit tests for the majority of the new code I added to make sure the whole process works as expected.

I'm open to any questions, comments or feedback! This code is mostly done but if you see anything else you think I should add or change I'd be happy to do it. Let me know what you guys think! :)

### CODE REVIEW

**Comment by bradacina** [comment]
Hi, what's the status of this PR? Is it being merged in, or will a separate package/project be created? Thanks.

**Comment by PaulParau** [comment]
On the long run, we intend to separate these reporters into different packages/projects. What we're probably going to do is take it one thing at a time: first merge this request and then separate it into a new project. Hope I'll get time to look over it soon, right now I'm focusing on launching a version with stable support for endpoint reports.

**Comment by Paccc** [comment]
@PaulParau I'd be happy to do the work to separate this reporter into a different package. There are a lot of new files added in this PR so it might not be desirable to merge it into the main Metrics.NET project, and honestly I think it would be best and make more sense if it were separated. If there's anything I can do to help let me know!

**Comment by PaulParau** [comment]
@Paccc That's great to hear! You're right, it will be easier to separate it sooner rather than later. If you're willing, I can create a new repository for the Graphite reporter and give you collaborator access so you can move the existing code there and setup the new package. How does that sound?

**Comment by Paccc** [comment]
@PaulParau That sounds good to me! I'll start working on that next week if you want to get the new repository setup over the weekend. Also, just make sure you create one for InfluxDB and not the Graphite reporter :)

**Comment by PaulParau** [comment]
@Paccc yeah, I meant to say InfluxDB :))

**Comment by PaulParau** [comment]
I've created the repo [here](https://github.com/Recognos/Metrics.NET.InfluxDB) and made you contributor with write access. Let me know if you encounter any issues.

**Comment by Paccc** [comment]
Thanks, Paul! I'll work on moving the InfluxDB code over to there and creating a nuget package for it sometime this week.

One question though, how should I version the nuget package? Should I have it match the Metrics.NET version or keep it separate and start it at v1.0.0?

Also, are there any other conventions or anything else I should be aware of, such as branching structure or tagging commits with the release version number?

**Comment by PaulParau** [comment]
Version: I don't think it makes much difference, but I prefer having it start from the Metrics.NET version (because that is the version of the InfluxDB reporter now, since it's part of the core library). They can diverge on further updates.

Conventions: on Metrics.NET, we keep a master branch where we'll have the latest stable version and a dev branch for prerelease stuff. Other than that we work with feature branches whenever a change is made. Commits are tagged with the release version number, you can see an example [in this commit](https://github.com/Recognos/Metrics.NET/commit/95dc5ea4468c7e4f80f8e39f640b0ac6175ae52e).

**Comment by naymore** [comment]
Maybe you should also consider separating your **domain logic** from **influxdb line protocol** related logic. The latter is a wheel which has been reinvented quite a few times on github. Why not use nuget for that. I was about to write an influxdb plugin myself - but this is good news ;-)

**Comment by Paccc** [comment]
@naymore The reason I "reinvented the wheel" instead of using an existing InfluxDB nuget package was because I wanted to implement this reporter without taking any external dependencies. The other reason is that I already have to convert the metrics values into an equivalent InfluxDB record representation which is more than half the work, and converting it to the line protocol from that point is trivial. 

Can you give me an example of what you mean by putting all the points in one measurement? I've tried to make the configuration fairly flexible and extensible already, but I'd be happy to try to add support for additional use cases as well.

**Comment by Paccc** [comment]
@PaulParau I finally got a chance to create the [InfluxDB repo](https://github.com/Recognos/Metrics.NET.InfluxDB) and upload the initial solution and build scripts. I split the repo into a master and dev branch, and tried to keep the folder structure as close to the Metrics.NET repo as possible. I used the default namespace `Metrics.InfluxDB` throughout the new solution.

Would you mind taking a look and testing things out (using `build.bat` and `create-nuget.bat`) whenever you get a chance, just to make sure I didn't overlook anything? I committed all the new code in the 'dev' branch. Assuming everything is okay I'll merge the code to master and we can do a release.

One potential issue we may have is that I noticed that there is already [an existing nuget package](https://www.nuget.org/packages/Metrics.NET.InfluxDB/) with the same name (Metrics.NET.InfluxDB). What do you recommend we do about this?

**Comment by naymore** [comment]
@Paccc I understand your motivation. I would still rather concentrate on an InfluxDbAdapter rather than writing to InfluxDB yourself. What if Line Protocol changes? Do you write in batches? Not writing in batches will put InfluxDB under severe load (from what I have seen). InfluxDB supports gzip compression which of course significantly reduces network traffic. Etc. pp.

> The measurement acts as a container for tags, fields, and the time column, and the measurement name is the description of the data that are stored in the associated fields. Measurement names are strings, and, for any SQL users out there, a measurement is conceptually similar to a table. 

In earlier versions of the Metrics.NET InfluxDB reporter I believe (not sure) there was a separate measurement per "subject under test".

**Comment by PaulParau** [comment]
@Paccc I managed to get a look at the new repo, nice work! These are the only things I noticed:

* `InfluxdbConfigExtensions` is still in the `Metrics` namespace. Wouldn't it be better if it was in the `Metrics.InfluxDB` namespace?
* The deprecated config extension methods have very similar signatures to the default ones (e.g. `WithInfluxDb(this MetricsReports reports, Uri influxdbUri, TimeSpan interval)` (deprecated) vs `WithInfluxDb(this MetricsReports reports, Uri influxDbUri, TimeSpan interval, MetricsFilter filter = null, Action<InfluxConfig> configFunc = null)`); you won't be able to call the second one without specifying values for the default parameters. On the same note, are the default extension methods required? As far as I can tell, they are equivalent to the HTTP ones, no? Maybe a solution here would be to remove the default ones (this way, they won't conflict with the old ones & you won't have any redundancies). What do you think?

I wasn't aware that there was another package for InfluxDB. I think the simplest approach here is to use another name (e.g. "Metrics.NET.InfluxDbReporting").

As for release, i propose we first do a new release of Metrics.NET in which built-in support for InfluxDB is removed, and then release a version of the new package which depends on the latest Metrics.NET.

**Comment by PaulParau** [comment]
I removed the old InfluxDB reporter from the core library in version v0.5.0-pre (Graphite and ElasticSearch as well) and published the new [InfluxDB nuget package](https://www.nuget.org/packages/Metrics.NET.InfluxDbReporting/). Any new issues & pull requests should go to the [new repo](https://github.com/Recognos/Metrics.NET.InfluxDB). @Paccc thanks again for all the work you did in separating this reporter.

**Pull request closed without merging**
